export { MCP_ICON_PATHS, MCP_ICON_VIEWBOX } from "./mcp-svg";
export {
  EDISON_E_PATH, EDISON_FRAME_PATH, EDISON_LOGO_VIEWBOX,
  EDISON_WATCH_FILL_PATH, EDISON_WATCH_STROKE_PATH,
} from "./edison-logo-svg";
